# Generated by Django 5.1.4 on 2024-12-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.CharField(max_length=150),
        ),
    ]
