# Generated by Django 5.1.4 on 2024-12-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('second_name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('subject', models.CharField(max_length=225)),
                ('message', models.TextField()),
            ],
        ),
    ]
